### PR TITLE
Add stopping of the connection after sending a mail to stop broken pi…

### PR DESCRIPTION
**Pull request by paulkned**
…pes from occurring

### CODE REVIEW

**Comment by YOzaz** [comment]
Actually, while I'm looking at this - it's completely different what this package does: instead of RESET command it stops whole transport after every send. We had a long discussion re. such behavior with Taylor and others, and many of them went this route - but it degrades performance a lot.
Meanwhile, can you tell me why try...catch does not work if reset fails? Here: https://github.com/YOzaz/Laravel-SwiftMailer/blob/master/src/YOzaz/LaravelSwiftmailer/Mailer.php#L182

**Comment by YOzaz** [comment]
@paulkned - would you be able to test new release? I've changed behaviour to STOP instead of RESET.
https://github.com/YOzaz/Laravel-SwiftMailer/releases/tag/v4.0.0

**Comment by paulkned** [comment]
@YOzaz this solves my problem, great! My fix was more of a hotfix-for-production kind of solution while this solution is way more elegant and thought out! :+1:

**Comment by YOzaz** [comment]
@paulkned you're welcome. My suggestion would be running in aggressive mode, and disable silent mode off (so you can catch failed emails). To be precise, initial setup would be:
```php
Mail::setModeBoth()->setSilent(false);
```
I may change these as a default in next release, not sure yet.

**Pull request closed without merging**
